DROP INDEX IF EXISTS IDX_GRAPH_THREAD_NAME_RELEASED

-- statement-boundary

DROP TABLE IF EXISTS GRAPH_CHECKPOINT CASCADE CONSTRAINTS

-- statement-boundary

DROP TABLE IF EXISTS GRAPH_THREAD CASCADE CONSTRAINTS

-- statement-boundary

CREATE TABLE IF NOT EXISTS GRAPH_THREAD (
   thread_id VARCHAR2(36) PRIMARY KEY,
   thread_name VARCHAR(255),
   is_released BOOLEAN DEFAULT FALSE NOT NULL
)

-- statement-boundary

CREATE INDEX IF NOT EXISTS IDX_GRAPH_THREAD_NAME_RELEASED
  ON GRAPH_THREAD(thread_name, is_released)

-- statement-boundary

CREATE TABLE IF NOT EXISTS GRAPH_CHECKPOINT (
   checkpoint_id VARCHAR2(36) PRIMARY KEY,
   thread_id VARCHAR2(36) NOT NULL,
   node_id VARCHAR(255),
   next_node_id VARCHAR(255),
   state_data JSON NOT NULL,
   state_content_type VARCHAR(100) NOT NULL,
   saved_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT GRAPH_FK_THREAD
       FOREIGN KEY(thread_id)
       REFERENCES GRAPH_THREAD(thread_id)
       ON DELETE CASCADE
)
